# Generated by Django 4.1.7 on 2023-02-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDeatils',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
